import streamlit as st
import pandas as pd
from docx import Document
import io

# دالة محسنة لقراءة الوورد
def safe_parse_word(doc_file):
    doc = Document(doc_file)
    questions = []
    for p in doc.paragraphs:
        text = p.text.strip()
        # نعتبر السطر سؤالاً إذا كان غير فارغ وطوله معقول
        if len(text) > 2:
            questions.append(text)
    return questions

st.set_page_config(page_title="SPSS Generator Pro", layout="wide")
st.title("🛠️ مولد سينتاكس SPSS المطور")

# منطقة رفع الملفات
col1, col2 = st.columns(2)
with col1:
    up_excel = st.file_uploader("1. ارفع ملف الإكسيل", type=['xlsx'])
with col2:
    up_word = st.file_uploader("2. ارفع ملف الوورد", type=['docx'])

if up_excel and up_word:
    try:
        # قراءة البيانات
        df = pd.read_excel(up_excel)
        word_questions = safe_parse_word(up_word)
        
        excel_cols = df.columns.tolist()
        
        st.info(f"تم العثور على {len(excel_cols)} أعمدة في إكسيل و {len(word_questions)} أسطر في وورد.")

        # بناء السينتاكس
        syntax_content = ["* SPSS Syntax Generated by Eng. Mohamed Tool.\n"]
        
        # الربط بناءً على العدد الأقل لتجنب الأخطاء
        limit = min(len(excel_cols), len(word_questions))
        
        for i in range(limit):
            col_name = excel_cols[i]
            question = word_questions[i].replace("'", "") # تنظيف النص من علامات الاقتباس
            syntax_content.append(f"VARIABLE LABELS {col_name} '{question}'.")
        
        syntax_content.append("\nEXECUTE.")
        final_syntax = "\n".join(syntax_content)

        # العرض والتحميل
        st.divider()
        st.subheader("النتائج:")
        
        # عرض الكود أولاً للتأكد من وجوده
        st.code(final_syntax, language='spss')
        
        # زر التحميل (مهم جداً: data تأخذ النص المولد)
        st.download_button(
            label="📥 تحميل ملف السينتاكس (.sps)",
            data=final_syntax,
            file_name="my_syntax.sps",
            mime="text/plain"
        )
        
    except Exception as e:
        st.error(f"حدث خطأ فني: {e}")
