import streamlit as st
import pandas as pd
import requests
from io import BytesIO
import re

# إعداد التطبيق
st.set_page_config(page_title="MBA SPSS Smart Solver", layout="wide")

st.title("🎓 المحرك الذكي المتكامل لحل امتحانات SPSS")
st.markdown("---")

# رابط ملف المنهج على GitHub (تأكد من تحديثه برابطك)
RULES_URL = "https://github.com/muhamedthabet866-dotcom/S/raw/refs/heads/main/spss_rules.xlsx"

@st.cache_data
def load_methodology(url):
    try:
        response = requests.get(url, timeout=10)
        return pd.read_excel(BytesIO(response.content))
    except:
        return None

rules_df = load_methodology(RULES_URL)

# --- الجانب الأيسر: الملفات والتعريفات ---
with st.sidebar:
    st.header("📁 1. ملف البيانات")
    data_file = st.file_uploader("ارفع ملف الإكسيل (Dataset)", type=['xlsx', 'xls'])
    if data_file:
        df = pd.read_excel(data_file)
        st.success(f"تم قراءة {len(df.columns)} متغير من الملف.")
    
    st.header("⚙️ 2. تعريف المتغيرات (Mapping)")
    st.info("اكتب التعريف كما هو في ورقة الامتحان")
    mapping_input = st.text_area("مثال:\nX1=account balance\nX6=city", 
                                value="X1=account balance\nX2=ATM transactions\nX4=debit card\nX5=interest\nX6=city", 
                                height=200)

# --- الجانب الأيمن: الأسئلة والحل ---
st.header("📝 3. أسئلة الامتحان")
questions_input = st.text_area("الصق الأسئلة هنا:", height=300, placeholder="1. Draw a bar chart for average account balance per city...")

if st.button("🚀 توليد الحل الإحصائي الذكي"):
    if not questions_input.strip() or rules_df is None:
        st.error("⚠️ يرجى إدخال الأسئلة والتأكد من اتصال ملف المنهج بـ GitHub.")
    else:
        # 1. تحويل الـ Mapping لقاموس ذكي
        mapping_dict = {}
        for line in mapping_input.split('\n'):
            if '=' in line:
                parts = line.split('=')
                mapping_dict[parts[1].strip().lower()] = parts[0].strip().upper()
        
        # ترتيب المتغيرات من الأطول للأقصر لتفادي الأخطاء
        sorted_var_names = sorted(mapping_dict.keys(), key=len, reverse=True)

        final_syntax = ["* Generated by MBA Smart Solver.\nSET DECIMALS=DOT.\n"]

        # 2. تقسيم ومعالجة الأسئلة
        # تقسيم بالسطر وتجاهل الأرقام والرموز في بداية السؤال
        lines = questions_input.split('\n')
        
        for q in lines:
            q_clean = q.strip()
            if not q_clean or len(q_clean) < 5: continue
            
            # تنظيف النص للبحث
            search_q = re.sub(r'^\d+[\.\)\s\t]+', '', q_clean).lower()
            
            matched = False
            # البحث في المنهج (الكلمات المفتاحية)
            for _, rule in rules_df.iterrows():
                keyword = str(rule['Keyword']).lower().strip()
                
                if keyword in search_q:
                    syntax_template = str(rule['Syntax_Template'])
                    
                    # استخراج المتغيرات المذكورة في هذا السؤال
                    found_vars = []
                    for name in sorted_var_names:
                        if name in search_q:
                            found_vars.append(mapping_dict[name])
                    
                    if found_vars:
                        # إزالة التكرار مع الحفاظ على الترتيب
                        unique_vars = list(dict.fromkeys(found_vars))
                        
                        # استبدال {var} بجميع المتغيرات المكتشفة
                        res_syntax = syntax_template.replace("{var}", " ".join(unique_vars))
                        
                        # استبدال {group} بآخر متغير (غالباً يكون متغير التصنيف مثل المدينة أو النوع)
                        if "{group}" in res_syntax:
                            group_var = unique_vars[-1] if len(unique_vars) > 1 else unique_vars[0]
                            res_syntax = res_syntax.replace("{group}", group_var)
                        
                        final_syntax.append(f"* Question: {q_clean}")
                        final_syntax.append(f"{res_syntax}\nEXECUTE.")
                        matched = True
                        break
            
            if not matched:
                final_syntax.append(f"* Question: {q_clean}\n* [!] لم يتم العثور على قاعدة مطابقة في المنهج.")

        st.subheader("✅ كود SPSS Syntax المولد:")
        st.code("\n".join(final_syntax), language="spss")
