import streamlit as st
import pandas as pd
import requests
from io import BytesIO
import re

st.set_page_config(page_title="SPSS MBA Solver", layout="wide")

st.title("🚀 المحرك الذكي لمنهج SPSS")

# --- الإعدادات وجلب المنهج من GitHub ---
GITHUB_RAW_URL = "https://github.com/muhamedthabet866-dotcom/S/raw/refs/heads/main/spss_rules.xlsx"

@st.cache_data
def load_rules(url):
    try:
        response = requests.get(url)
        return pd.read_excel(BytesIO(response.content))
    except:
        return None

rules_df = load_rules(GITHUB_RAW_URL)

# --- الواجهة ---
col1, col2 = st.columns(2)

with col1:
    st.subheader("⚙️ تعريف المتغيرات (Mapping)")
    # مثال لما يتم إدخاله بناءً على ملفاتك
    mapping_input = st.text_area("انسخ المتغيرات من أسفل ورقة الامتحان:", 
                                value="X2=League\nX5=Salary\nX11=Surface\nX7=Wins", height=250)

with col2:
    st.subheader("📝 أسئلة الامتحان")
    questions_input = st.text_area("الصق الأسئلة هنا:", 
                                  value="Draw a bar chart for average salary for each league\nTest the normality of salary", height=250)

if st.button("🚀 توليد الحل الكامل"):
    if rules_df is not None:
        # 1. تحويل الـ Mapping لقاموس (Name -> Code)
        mapping_dict = {}
        for line in mapping_input.split('\n'):
            if '=' in line:
                code, name = line.split('=')
                mapping_dict[name.strip().lower()] = code.strip().upper()

        final_syntax = ["* Generated by MBA Solver.\nSET SEED=1234567."]
        
        # 2. تحليل الأسئلة
        questions = questions_input.split('\n')
        for q in questions:
            if not q.strip(): continue
            
            matched = False
            for _, rule in rules_df.iterrows():
                if rule['Keyword'].lower() in q.lower():
                    syntax = rule['Syntax_Template']
                    
                    # استبدال المتغيرات الذكي
                    for name, code in mapping_dict.items():
                        if name in q.lower():
                            syntax = syntax.replace("{var}", code).replace("{group}", code)
                    
                    final_syntax.append(f"\n* Question: {q}\n{syntax}\nEXECUTE.")
                    matched = True
                    break
            
            if not matched:
                final_syntax.append(f"\n* Question: {q}\n* [يرجى مراجعة المنهج يدوياً لهذا السؤال]")

        st.subheader("✅ كود SPSS Syntax المولد:")
        st.code("\n".join(final_syntax), language="spss")
    else:
        st.error("فشل في جلب ملف المنهج من GitHub. تأكد من الرابط.")

